### ISSUE TITLE
File upload tests fail in TeamCity

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#198]
@PatrykSzwer could you pls take a look? For example today's build: http://teamcity.starcounter.org/viewLog.html?buildId=36231&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Develop

![image](https://user-images.githubusercontent.com/566463/32340723-b58177c0-bffb-11e7-9272-49a38a0a6fec.png)

**Comment by PatrykSzwer** [comment]
I've done some investigation and turns out that It's Starcounter's update fault. After updating on version 2.3.1.7688 Handler responsive for handling web socket disconnection stopped working. @alemoi could You provide us some help here?
This fragment is not working anymore:
https://github.com/Starcounter/KitchenSink/blob/develop/src/KitchenSink/HandleFile.cs#L79

**Comment by alemoi** [comment]
> Handler responsive for handling web socket disconnection stopped working.

Do you mean its not called? Or some other kind of failure?

**Comment by PatrykSzwer** [comment]
Exactly, It's not even called.

**Comment by alemoi** [comment]
Will look into it tomorrow!

**Comment by warpech** [comment]
@PatrykSzwer is it fixed now?

**Comment by alemoi** [comment]
Seems working fine!
