### ISSUE TITLE
Remove specific classes for tests

### ISSUE THREAD

**Issue by tomalec** [Starcounter/KitchenSink#242]
### Steps to reproduce
1. Open code at https://github.com/Starcounter/KitchenSink/blob/d1a1a082c00662a98b6a457024a2775a60e38eb9/src/KitchenSink/wwwroot/KitchenSink/TextareaPage.html#L7-L9

### Expected result
The code should be as clean as possible to showcase Starcounter features

### Actual result
The elements have `class="kitchensink-test-bio-reaction-label"` attributes just for Selenium tests.

I believe, it may be confusing for newcomers, for sure it's additional code that may blur the picture out of data propagation.

I'm really afraid readers/devs may consider those class an example of classes to be used for light DOM styling, and we are actually trying to discourage such use.

Also, is `test-value` attribute also needed just for tests?

### Technical information
If we need precise selector for Selenium, maybe `[slot="kitchensink/textarea-label"]` would be enough.

**Comment by warpech** [comment]
Using `[slot="kitchensink/textarea-label"]` as the selector for Selenium is a great idea, thanks!

I am afraid `test-value` attribute is needed. At least, it was needed at the time of writing the tests. But we can check that again because that was in the time of Polymer 1.x.

@kegor could you please work on this? 

I propose to target a PR at `master-2.4` branch to make sure we can check that it is passing. After it is done, we will do a merge of `master-2.4` to `underwear-2.4` with a manual resolution of the conflicts.

**Comment by kegor** [comment]
Closed because the fix was merged in #243.

**Comment by tomalec** [comment]
It seems we still have unprefixed test-specific classes like 
- [ ] https://github.com/Starcounter/KitchenSink/blob/master-2.4/test/KitchenSink.Tests/Ui/TablePage.cs#L17-L21
- [ ] https://github.com/Starcounter/KitchenSink/blob/master-2.4/src/KitchenSink/wwwroot/KitchenSink/TablePage.html#L7
- [ ] https://github.com/Starcounter/KitchenSink/blob/master-2.4/test/KitchenSink.Tests/Ui/FileUploadPage.cs#L14

**Comment by kegor** [comment]
Closed because the fix was merged in the #249.
