### ISSUE TITLE
DatepickerPage_SelectDate test sometimes fails

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#269]
Sometimes the build fails on the `DatepickerPage_SelectDate` test. For example: https://teamcity.starcounter.org/viewLog.html?buildId=50715&buildTypeId=Apps_KitchenSink_KitchenSinkMaster24branchWithStarcounterDevelopNightly

@kegor could you pls investigate that?

<img width="1139" alt="screen shot 2018-03-26 at 08 58 47" src="https://user-images.githubusercontent.com/566463/37891327-359c22f4-30d4-11e8-9e54-47cfc638b2d0.png">

**Comment by kegor** [comment]
I think that the problem here is in time that datepicker spends on changing the default date on the selected one in the test:
![datepicker_selectdate_test](https://user-images.githubusercontent.com/17431807/37901249-5b8b87f0-30f9-11e8-8c84-5beb06c51f2a.gif)
I think we can either replace `Assert`'s on `WaitUntil` or add one `WaitUntil` before all `Assert`'s, it will wait while datepicker will be closed again.

**Comment by kegor** [comment]
Closed because initial fixes were merged in #270, and new #273 was opened.
